name: Build U-Boot

on:
  push:

  workflow_dispatch:

jobs:
  build:
    name: Build U-Boot
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache
        id: cache
        uses: actions/cache@v3
        with:
          path: gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu
          key: gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu
      - name: Create directory
        run: |
          mkdir u-boot
          find . -maxdepth 1 -not -name . -not -name .. -not -name .github -not -name mkgpt.sh -not -name u-boot -exec mv {} u-boot/ \;
      - name: Install toolchain
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: u-boot
        run: |
          sudo apt install kpartx
          curl -#LO https://releases.linaro.org/components/toolchain/binaries/6.3-2017.05/aarch64-linux-gnu/gcc-linaro-6.3.1-2017.05-x86_64_aarch64-linux-gnu.tar.xz
          tar xvf gcc-linaro-6.3.1-2017.05-x86_64_aarch64-linux-gnu.tar.xz -C ./
          sudo ln -s $(pwd)/gcc-linaro*aarch64-linux-gnu /usr/local/gcc-linaro_aarch64-linux-gnu
          git clone https://github.com/rockchip-linux/rkbin --depth 1 ../rkbin

      - name: Build U-Boot
        working-directory: u-boot
        run: |
          export ARCH=arm64
          export CROSS_COMPILE=/usr/local/gcc-linaro_aarch64-linux-gnu/bin/aarch64-linux-gnu-
          make evb-rk3399_defconfig
          make dtbs
          ./make.sh evb-rk3399
      - name: Make sd card image
        run: |
          bash mkgpt.sh
          sudo kpartx -av gpt.img
          dd if=u-boot/u-boot.bin of=loop3p2 bs=4096
          dd if=u-boot/trust.bin of=loop3p3 bs=4096

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: JJ31-uboot
          path: |
            u-boot/*.bin 
            u-boot/*.img
          if-no-files-found: ignore
